name: "test VS 2019"

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2019
#    env:
#      SHFB_VERSION: V2021.4.9.0
#      SHFB_ROOT: C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
    
    steps:
 
    - name: Install checkout
      uses: actions/checkout@v2
      
    - name: Install create-solution
      uses: ./
      with:
        name: DemotSolution
        version: 2019
        
    - name: Test
      run: |
           echo SHFBROOT: %SHFBROOT% 
           echo TEMP: %TEMP%
           type %TEMP%\vsixinst.log
      shell: cmd