name: "test VS 2019"

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2019
#    env:
#      SHFB_VERSION: V2021.4.9.0
#      SHFB_ROOT: C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
    
    steps:
 
    - name: Install checkout
      uses: actions/checkout@v2
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3
      
    - name: Create Solution
      uses: ./
      with:
        name: DemoSolution
        projects: Tests\CS6\CS6.csproj,Tests\CS4\CS4.csproj
        #configurations: Debug|Any CPU,Release|Any CPU
        
    - name: Show Solution
      run: type DemoSolution.sln
      shell: cmd
      
    - name: MSBuild of solution
      run: msbuild DemoSolution.sln /p:configuration="Release" /m /verbosity:minimal